"use client";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense, useState } from "react";
import Loading from "./loading";
import { cartContext } from "../app/_context/cartContext";

const inter = Roboto({ subsets: ["latin"], weight: "500" });

// export const metadata = {
//   title: "Courses Online",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  return (
    <ClerkProvider>
      <cartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            <Suspense fallback={<Loading />}>{children}</Suspense>
            <Footer />
          </body>
        </html>
      </cartContext.Provider>
    </ClerkProvider>
  );
}
